#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Casus_Jaar_2_Blok_1_Groep_3.Resource", IsApplication=true)]

namespace Casus_Jaar_2_Blok_1_Groep_3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AccountDeleteIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int DutchFlag = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int EnglishFlag = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Favorite = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Home = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Inloggenicon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Instellingen = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Netflix = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ParentVision = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int SearchIcon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int TerugKnnop2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int TerugKnop = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int TerugKnop3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Terugknop4 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int TerugKnop5 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int UserAdd = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Youtube = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Youtube2 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Youtube3 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Ziggo = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Ziggo2 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Ziggo3 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Ziggo4 = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05002e
			public const int btnAccountToevoegen = 2131034158;
			
			// aapt resource value: 0x7f050030
			public const int btnAccountVerwijderen = 2131034160;
			
			// aapt resource value: 0x7f05002c
			public const int btnFavorieten = 2131034156;
			
			// aapt resource value: 0x7f050006
			public const int btnInloggen = 2131034118;
			
			// aapt resource value: 0x7f050036
			public const int btnInstMenu = 2131034166;
			
			// aapt resource value: 0x7f050041
			public const int btnInstellingen = 2131034177;
			
			// aapt resource value: 0x7f050002
			public const int btnInstellingenAccT = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int btnInstellingenAccV = 2131034121;
			
			// aapt resource value: 0x7f050019
			public const int btnInstellingenFav = 2131034137;
			
			// aapt resource value: 0x7f050045
			public const int btnInstellingenOuder = 2131034181;
			
			// aapt resource value: 0x7f050039
			public const int btnInstellingenSearch = 2131034169;
			
			// aapt resource value: 0x7f05002a
			public const int btnInstellingenTerug = 2131034154;
			
			// aapt resource value: 0x7f050004
			public const int btnLogoAccount = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int btnMenuAccV = 2131034122;
			
			// aapt resource value: 0x7f050018
			public const int btnMenuFav = 2131034136;
			
			// aapt resource value: 0x7f050046
			public const int btnMenuOuder = 2131034182;
			
			// aapt resource value: 0x7f05003b
			public const int btnMenuSearch = 2131034171;
			
			// aapt resource value: 0x7f050042
			public const int btnNetflix = 2131034178;
			
			// aapt resource value: 0x7f050013
			public const int btnNetflixAccountVerwijderen = 2131034131;
			
			// aapt resource value: 0x7f05001b
			public const int btnNetflixFavorieten1 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int btnNetflixFavorieten2 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int btnNetflixFavorieten3 = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int btnNetflixFavorieten4 = 2131034142;
			
			// aapt resource value: 0x7f05004a
			public const int btnOuderActiveren = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int btnOuderDeactiveren = 2131034187;
			
			// aapt resource value: 0x7f050032
			public const int btnOuderlijkToezicht = 2131034162;
			
			// aapt resource value: 0x7f05003a
			public const int btnSearchBackT = 2131034170;
			
			// aapt resource value: 0x7f050034
			public const int btnTaalVeranderen = 2131034164;
			
			// aapt resource value: 0x7f050003
			public const int btnTerugNaarMenuAccT = 2131034115;
			
			// aapt resource value: 0x7f050038
			public const int btnTerugOpenProgram = 2131034168;
			
			// aapt resource value: 0x7f050043
			public const int btnYoutube = 2131034179;
			
			// aapt resource value: 0x7f050011
			public const int btnYoutubeAccountVerwijderen = 2131034129;
			
			// aapt resource value: 0x7f050020
			public const int btnYoutubeFavorieten1 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int btnYoutubeFavorieten2 = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int btnYoutubeFavorieten3 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int btnYoutubeFavorieten4 = 2131034147;
			
			// aapt resource value: 0x7f050044
			public const int btnZiggo = 2131034180;
			
			// aapt resource value: 0x7f050015
			public const int btnZiggoAccountVerwijderen = 2131034133;
			
			// aapt resource value: 0x7f050025
			public const int btnZiggoFavorieten1 = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int btnZiggoFavorieten2 = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int btnZiggoFavorieten3 = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int btnZiggoFavorieten4 = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int btnZoeken = 2131034153;
			
			// aapt resource value: 0x7f05003f
			public const int btnZoekenZoeken = 2131034175;
			
			// aapt resource value: 0x7f050049
			public const int etOuderCode = 2131034185;
			
			// aapt resource value: 0x7f050008
			public const int etPassword = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int etUsername = 2131034119;
			
			// aapt resource value: 0x7f05003d
			public const int etZoekveld = 2131034173;
			
			// aapt resource value: 0x7f050040
			public const int linearLayout1 = 2131034176;
			
			// aapt resource value: 0x7f05002d
			public const int txtAccAddIconMenu = 2131034157;
			
			// aapt resource value: 0x7f05004c
			public const int txtCode = 2131034188;
			
			// aapt resource value: 0x7f05002f
			public const int txtDelAccIconMenu = 2131034159;
			
			// aapt resource value: 0x7f050017
			public const int txtFavIconFav = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int txtFavorieten = 2131034134;
			
			// aapt resource value: 0x7f05002b
			public const int txtFavorietenIcoonMenu = 2131034155;
			
			// aapt resource value: 0x7f050033
			public const int txtFlagIconMenu = 2131034163;
			
			// aapt resource value: 0x7f050035
			public const int txtHomeIcoonMenu = 2131034165;
			
			// aapt resource value: 0x7f05003c
			public const int txtHoofdSearch = 2131034172;
			
			// aapt resource value: 0x7f050005
			public const int txtInloggenKnopjeIcon = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int txtInstellingenAccountToevoegen = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int txtInstellingenAccountToevoegenIcon = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int txtInstellingenAccountVerwijderen = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int txtInstellingenAccountVerwijderenIcon = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int txtNetflixAccV = 2131034123;
			
			// aapt resource value: 0x7f050012
			public const int txtNetflixAccountVerwijderen = 2131034130;
			
			// aapt resource value: 0x7f05001a
			public const int txtNetflixFavorieten = 2131034138;
			
			// aapt resource value: 0x7f050037
			public const int txtOpenProgram = 2131034167;
			
			// aapt resource value: 0x7f050047
			public const int txtOuderZicht = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int txtOuderZichtIconIcon = 2131034184;
			
			// aapt resource value: 0x7f050031
			public const int txtParentVisionIconMenu = 2131034161;
			
			// aapt resource value: 0x7f05003e
			public const int txtSearch = 2131034174;
			
			// aapt resource value: 0x7f05000c
			public const int txtYoutubeACCV = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int txtYoutubeAccountVerwijderen = 2131034128;
			
			// aapt resource value: 0x7f05001f
			public const int txtYoutubeFavorieten = 2131034143;
			
			// aapt resource value: 0x7f05000d
			public const int txtZiggoACCV = 2131034125;
			
			// aapt resource value: 0x7f050014
			public const int txtZiggoAccountVerwijderen = 2131034132;
			
			// aapt resource value: 0x7f050024
			public const int txtZiggoFavorieten = 2131034148;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LayoutAccountToevoegen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LayoutAccountVerwijderen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LayoutFavorieten = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LayoutInstellingen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LayoutOpenProgram = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LayoutSearch = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int OuderZicht = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
