#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Casus_Jaar_2_Blok_1_Groep_3.Resource", IsApplication=true)]

namespace Casus_Jaar_2_Blok_1_Groep_3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04002a
			public const int btnAccountToevoegen = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int btnAccountVerwijderen = 2130968619;
			
			// aapt resource value: 0x7f040029
			public const int btnFavorieten = 2130968617;
			
			// aapt resource value: 0x7f040003
			public const int btnInloggen = 2130968579;
			
			// aapt resource value: 0x7f040030
			public const int btnInstellingen = 2130968624;
			
			// aapt resource value: 0x7f040000
			public const int btnInstellingenAccT = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int btnInstellingenAccV = 2130968582;
			
			// aapt resource value: 0x7f04000b
			public const int btnInstellingenAccountToevoegen = 2130968587;
			
			// aapt resource value: 0x7f040027
			public const int btnInstellingenBlok = 2130968615;
			
			// aapt resource value: 0x7f040014
			public const int btnInstellingenFav = 2130968596;
			
			// aapt resource value: 0x7f040028
			public const int btnInstellingenTerug = 2130968616;
			
			// aapt resource value: 0x7f040002
			public const int btnLogoAccount = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int btnMenuAccV = 2130968583;
			
			// aapt resource value: 0x7f040013
			public const int btnMenuFav = 2130968595;
			
			// aapt resource value: 0x7f040031
			public const int btnNetflix = 2130968625;
			
			// aapt resource value: 0x7f04000f
			public const int btnNetflixAccountVerwijderen = 2130968591;
			
			// aapt resource value: 0x7f040016
			public const int btnNetflixFavorieten1 = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int btnNetflixFavorieten2 = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int btnNetflixFavorieten3 = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int btnNetflixFavorieten4 = 2130968601;
			
			// aapt resource value: 0x7f040024
			public const int btnNetflixInstellingen = 2130968612;
			
			// aapt resource value: 0x7f04002c
			public const int btnTaalVeranderen = 2130968620;
			
			// aapt resource value: 0x7f040001
			public const int btnTerugNaarMenuAccT = 2130968577;
			
			// aapt resource value: 0x7f04002e
			public const int btnTerugOpenProgram = 2130968622;
			
			// aapt resource value: 0x7f040032
			public const int btnYoutube = 2130968626;
			
			// aapt resource value: 0x7f04000d
			public const int btnYoutubeAccountVerwijderen = 2130968589;
			
			// aapt resource value: 0x7f04001b
			public const int btnYoutubeFavorieten1 = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int btnYoutubeFavorieten2 = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int btnYoutubeFavorieten3 = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int btnYoutubeFavorieten4 = 2130968606;
			
			// aapt resource value: 0x7f040025
			public const int btnYoutubeInstellingen = 2130968613;
			
			// aapt resource value: 0x7f040033
			public const int btnZiggo = 2130968627;
			
			// aapt resource value: 0x7f040011
			public const int btnZiggoAccountVerwijderen = 2130968593;
			
			// aapt resource value: 0x7f040020
			public const int btnZiggoFavorieten1 = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int btnZiggoFavorieten2 = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int btnZiggoFavorieten3 = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int btnZiggoFavorieten4 = 2130968611;
			
			// aapt resource value: 0x7f040026
			public const int btnZiggoInstellingen = 2130968614;
			
			// aapt resource value: 0x7f040005
			public const int etPassword = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int etUsername = 2130968580;
			
			// aapt resource value: 0x7f04002f
			public const int linearLayout1 = 2130968623;
			
			// aapt resource value: 0x7f040012
			public const int txtFavorieten = 2130968594;
			
			// aapt resource value: 0x7f040008
			public const int txtNetflixAccV = 2130968584;
			
			// aapt resource value: 0x7f04000e
			public const int txtNetflixAccountVerwijderen = 2130968590;
			
			// aapt resource value: 0x7f040015
			public const int txtNetflixFavorieten = 2130968597;
			
			// aapt resource value: 0x7f04002d
			public const int txtOpenProgram = 2130968621;
			
			// aapt resource value: 0x7f040009
			public const int txtYoutubeACCV = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int txtYoutubeAccountVerwijderen = 2130968588;
			
			// aapt resource value: 0x7f04001a
			public const int txtYoutubeFavorieten = 2130968602;
			
			// aapt resource value: 0x7f04000a
			public const int txtZiggoACCV = 2130968586;
			
			// aapt resource value: 0x7f040010
			public const int txtZiggoAccountVerwijderen = 2130968592;
			
			// aapt resource value: 0x7f04001f
			public const int txtZiggoFavorieten = 2130968607;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int LayoutAccountToevoegen = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int LayoutAccountVerwijderen = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int LayoutFavorieten = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int LayoutInstellingen = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int LayoutOpenProgram = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int main = 2130837509;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
